### ISSUE TITLE
U-Net

### ISSUE THREAD

**Issue by 123ioup** [Easonyesheng/CCS#11]
Hi,Why does the model training only use the most basic U-Net network structure and not use a better model for training?Does the improvement of U-Net model affect the results of diagonal point detection

**Comment by Easonyesheng** [comment]
We didn't try other models at that time, as the corner detection task is easy and UNet is enough.
But better model may lead to better results, like diffusion.

**Comment by 123ioup** [comment]
> We didn't try other models at that time, as the corner detection task is easy and UNet is enough. But better model may lead to better results, like diffusion.
Thank you very for your answer
