### ISSUE TITLE
How to train？

### ISSUE THREAD

**Issue by xuefeng1130** [Easonyesheng/CCS#13]
<img width="1098" alt="image" src="https://github.com/Easonyesheng/CCS/assets/113966288/fcb4f35c-40f5-401d-bdf5-a26ce53fc52d">

How to set the parameters appropriately？
Which one to use for the training dataset?

**Comment by xuefeng1130** [comment]
To train our networks, we generate massive chessboard images (480 × 480) with ground truth corner heatmaps and camera parameters (focal length, principal points and scale) in pixel (100 ≤ fx, fy ≤ 300; 120 ≤ px, py ≤ 360; 1 ≤ s ≤ 5). Moreover, noise, bad lighting, distortion and fake background using TUM dataset [31] are applied as data augmentation. Specifically, the image distortion level is decided by parameters k0, k1 and k2.

How do I generate the chessboard image (480*480) and which version of TUM dataset to download and what to do with it?
I didn't understand the steps of training, please give me some help, thanks!

**Comment by xuefeng1130** [comment]
<img width="548" alt="image" src="https://github.com/Easonyesheng/CCS/assets/113966288/86dedecf-ca43-4f78-94a5-f35828e0f757">
<img width="749" alt="image" src="https://github.com/Easonyesheng/CCS/assets/113966288/b5de5da3-37a3-4952-8321-c7709f355119">

Are these paths set up correctly for me? What does each path do?
Is it a 480*480 image that I need to provide? How many?
What about the TUM dataset?

**Comment by Easonyesheng** [comment]
bg_img_list is the path list of background images, which is used as the background of generated checkerboard images.
These background images are resized to the fix size of generated image (like 480x480).
In our paper, we use the images in TUM dataset as the background images.
In practices, you can use your own background image which should be close to your calibration environment.

**Comment by xuefeng1130** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，我的邮箱已接收到您发来的邮件。待我处理后给您回复。
