### ISSUE TITLE
Running the demo gives an error

### ISSUE THREAD

**Issue by xuefeng1130** [Easonyesheng/CCS#15]
<img width="1139" alt="image" src="https://github.com/Easonyesheng/CCS/assets/113966288/270b50f0-953a-4b32-b453-f7e6b624460d">

**Comment by Easonyesheng** [comment]
Can you.provide more information, like your path settings?

**Comment by xuefeng1130** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，我的邮箱已接收到您发来的邮件。待我处理后给您回复。
