### ISSUE TITLE
UNet

### ISSUE THREAD

**Issue by 123ioup** [Easonyesheng/CCS#19]
我尝试用使用其它UNet模型去训练，检测的结果为什么是这种，是训练的次数太少了吗，希望能够得到您的帮助
![1e5e058e768b06f7385d27907b3de27](https://github.com/Easonyesheng/CCS/assets/140148449/a0e79457-68fb-4266-a9c6-6efa16554b99)

**Comment by 123ioup** [comment]
![image](https://github.com/Easonyesheng/CCS/assets/140148449/a12266f3-988f-42ac-81f6-a68970568eca)

**Comment by Easonyesheng** [comment]
很奇怪，看上去感觉网络没有收敛，或许可以增加数据量试试看

**Comment by 123ioup** [comment]
作者您好，我想请教一下论文中的Corner Detection Accuracy (pixels)是怎么计算的，是对于所有检测到的角点计算的平均像素误差吗？是每个角点的像素误差相加然后除以角点个数吗
还有另外一个问题，每个角点的像素误差可以计算吗，比如想要计算角点误差区间在0-0.4pixel的角点个数，可以计算得到吗？
感谢作者在百忙 之中可以帮忙解答一下我遇到的问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Easonyesheng/CCS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月6日(星期四) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Easonyesheng/CCS] UNet (Issue #19)





 
Closed #19 as completed.
