### ISSUE TITLE
Encountered a small issue while training the “train_DistCorr.py”  file.

### ISSUE THREAD

**Issue by cheny00** [Easonyesheng/CCS#21]
The operation is as follows：

1、train_txt_path = r'E:\project\DIC_Detection\self\hub\CCS\CCS-main\dataset_img2.txt'
Path Example,
G:\stereoCalibration\dataset\composite\480X480_CCS\test\img\10-0.jpg G:\stereoCalibration\dataset\composite\480X480_CCS\test\heatmap\10-0.npy

2、when running “train_DistCorr.py”
![image](https://github.com/Easonyesheng/CCS/assets/93637713/44ff48be-5b5f-449f-8a0e-096f357a400d)

"loss_util.py" happen
![image](https://github.com/Easonyesheng/CCS/assets/93637713/7407e48f-b02f-4acb-b6e5-90d0bf8371b2)

How can I solve the problem?
Is the dimension a problem with loading data ”train_txt_path “ files, or is it somewhere else? Where is the detection data generated （corners_before[:,0]） for corner loading? What are the dimensions referring to?

Looking forward to your recovery.

**Comment by Easonyesheng** [comment]
It may be caused by different numpy versions. This part is to load corner data generated by our [code](https://github.com/Easonyesheng/CCS/tree/main/dataset). You can investigate the generated corner data.
