### ISSUE TITLE
Corner Detection Accuracy 

### ISSUE THREAD

**Issue by 123ioup** [Easonyesheng/CCS#22]
作者您好，我想请教一下论文中的Corner Detection Accuracy (pixels)是怎么计算的，是对于所有检测到的角点计算的平均像素误差吗？是每个角点的像素误差相加然后除以角点个数这样计算的吗
![1718457595083](https://github.com/Easonyesheng/CCS/assets/140148449/a9393648-a6de-495a-8562-5369702dc41a)

**Comment by 123ioup** [comment]
![1718524716130](https://github.com/Easonyesheng/CCS/assets/140148449/c07be242-c8f7-4ef7-a054-e96317037c30)
这里跑出来的coner error是怎么计算的，是每张棋盘格图片中所有角点误差的平均值吗，还是所有角点误差的和呢，希望作者能够帮忙解答一下。非常感谢

**Comment by Easonyesheng** [comment]
1. 是的
2. 是误差的平均值

**Comment by 123ioup** [comment]
感谢您的回答

**Comment by 123ioup** [comment]
![a29843f21c58c18ce49a46afa0418ed](https://github.com/Easonyesheng/CCS/assets/140148449/3baefbc3-1197-4655-bb6f-711b85c6fbe8)
![18623d0ee40eb5e66b0e63371f1dafd](https://github.com/Easonyesheng/CCS/assets/140148449/2a0b3dbf-9d57-4aab-a9d2-af78f1605808)
这里GT文件夹里的npy文件是怎么得到的，我用data_generator.py生成的.npy去运行，这里显示是全0的数组。希望能够得到您的帮助

**Comment by 123ioup** [comment]
不好意思，是自己的操作失误，问题已经解决了
