### ISSUE TITLE
畸变校正问题

### ISSUE THREAD

**Issue by qianxiaosyu** [Easonyesheng/CCS#23]
你好，我最近读了您的文章并在复现代码中，训练train_DistCorr.py（order：3，dist_model：radi）后，利用训练后的权重文件在 rectify.py 文件进行测试，校正的效果并不是很好，数据集都是通过data_generator.py生成的，不知道哪出问题了，还请您解疑，谢谢！
（路径示例：D:\pycharm\Pycharm\ccs2\CCS-main\dataset\test\dist_img\2-0.jpg D:\pycharm\Pycharm\ccs2\CCS-main\dataset\test\dist_corner\2-0.npy）

**Comment by qianxiaosyu** [comment]
另外，训练train_DistCorr.py（order：1，dist_model：radi）后，利用训练后的权重文件在 rectify.py 文件进行测试，就校正成功了。 The average PSNR=20.79224227117442，The average SSIM=0.8083858395885156

**Comment by Easonyesheng** [comment]
是不是没有收敛，order高的模型更复杂一些，比如简单的模型好训练

**Comment by qianxiaosyu** [comment]
你当时用的多少训练集图片，训练了多少个epoch。应该是收敛了吧，我的trainlog如下，验证损失稳定在0.0014至0.0019之间，没有显著下降趋势。然而在测试时，生成图像 'dist_k' : [1, -0.45, 0.2] ，而预测参数是the parameters are: [ 0.99421585  0.0202473  -0.02511768]。在你论文中提到在失真模型中随机采样 3 个参数，生成大量
失真的棋盘图像，输出参数数设为 5。意思是模型输出5个参数嘛

**Comment by qianxiaosyu** [comment]
[trainlog2.txt](https://github.com/user-attachments/files/15895401/trainlog2.txt)
这是我的trainlog

**Comment by qianxiaosyu** [comment]
作者能解疑一下嘛，谢谢拉！

**Comment by Easonyesheng** [comment]
我觉得应该还是训练的问题，你可以尝试生成更多的数据，同时数据内部的畸变类型也要很丰富。我记得当时是用了8K每组的24组不同畸变的图像作为数据集

**Comment by qianxiaosyu** [comment]
也就是总共8000*24个畸变图像嘛

**Comment by Easonyesheng** [comment]
对哦
