### ISSUE TITLE
Dataset generation

### ISSUE THREAD

**Issue by alien19** [Easonyesheng/CCS#3]
Hello, 
I wanted to generate a dataset with another resolution and hence, another parameters but when I changed the values in the data_generateor.py it gives the following error 
![image](https://user-images.githubusercontent.com/42179967/220578789-9cf0bb5c-6df7-4685-bd05-36092db7afe5.png)

any help is appreciated!

**Comment by Easonyesheng** [comment]
Sorry, I cannot see your image.
You may need to upload your image again.

**Comment by alien19** [comment]
@Easonyesheng please recheck

**Comment by Easonyesheng** [comment]
It seems like that the draw_fix_checkboard function returns None.
Maybe your parameters make the chessboard appear outside the image.
Please check the line 474 of DataGenerator.py.

**Comment by alien19** [comment]
Yes I'm aware of that, the random numbers of the parameters generated according to my range doesn't abide by the condition https://github.com/Easonyesheng/CCS/blob/e2ed5d23d84d16817b1433258fd7c3370e3deaca/dataset/DataGenerator.py#L262
so I wanted to understand more about it!

Edit: I'm interested in generating images with size 2800 which is relatively larger than mentioned in the demo i.e 480

**Comment by Easonyesheng** [comment]
p_ ic is a **p**oint in the **i**mage **c**oordinate system.
L262 is used to determine if the point inside the image.

If you want to generate image with larger size, you should calculate the parameters like specific camera focal length and the distance between camera and chessboard, etc to keep the chessboard inside the image.

**Comment by alien19** [comment]
thanks @Easonyesheng I already got what u have already explained, but what I didn't understand is the fixed value of the d in **draw_fix_checkboard**.
I really tried multiple combinations of parameters and image size but with still stuck with the error

**Comment by Easonyesheng** [comment]
The d is the distance between chessboard and camera center, which is depicted in the [image](https://github.com/Easonyesheng/CCS/tree/main/dataset#chessboard-images-generation-with-camera-parameters).
The d should be changed if you want a larger image, and it is the ratio of d that matters (ratio between the standard and random placed chessboard distance).
I think you should pre-calculate the parameter range first, based on the camera projection model and the [description](https://github.com/Easonyesheng/CCS/tree/main/dataset#chessboard-images-generation-with-camera-parameters).
