### ISSUE TITLE
How can i use our own chessboard pics to get the results?

### ISSUE THREAD

**Issue by BaoziElisa** [Easonyesheng/CCS#5]
Hi,I would like to ask if it is possible to input the checkerboard pictures taken by myself so as to obtain calibration results in your method. I can't find the model file. I don't know how to run it, sorry, looking forward to your reply.

**Comment by Easonyesheng** [comment]
For better accuracy, a specific model trained on synthetic images which are close to your own data and calibration environment is better, though time consumption is large.
So if you pursue accuracy, you should train your own model.
If you just want to test calibration, you can use the RANSAC-based calibration algorithm in our code.
We will upload a pre-trained corner detection model later, you can use that to process your image.
For distortion correction, our method is sensitive to different chessboards, so a specifically-trained model is better.
