### ISSUE TITLE
How to find the distortion correction model?

### ISSUE THREAD

**Issue by baolongqishi** [Easonyesheng/CCS#6]
![image](https://github.com/Easonyesheng/CCS/assets/89435058/6895ffbe-47b4-4e0b-8bab-b510c432a41c)
I saw the CornerDetection model file, but did not find the distortion correction model file. May I ask where I should get it?

**Comment by Easonyesheng** [comment]
Hello
We recommend you to train a correction model using our data generation code and training scripts.
We've try to upload the pretrained correction model, but it is too big to directly upload by git, and this correction method is also sensitive to the specific chessboard pattern.
So train your own model is better.

**Comment by baolongqishi** [comment]
Ok, I will try it first. Thank you very much for your reply.



---Original---
From: "Eason ***@***.***&gt;
Date: Tue, Jun 27, 2023 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Easonyesheng/CCS] How to find the distortion correction model?(Issue #6)




 
We recommend you to train a correction model using our data generation code and training scripts.
 We've try to upload the pretrained correction model, but it is too big to directly upload by git, and this correction method is also sensitive to the specific chessboard pattern.
 So train your own model is better.

**Comment by xuefeng1130** [comment]
> Ok, I will try it first. Thank you very much for your reply.
> […](#)
> ---Original--- From: "Eason ***@***.***&gt; Date: Tue, Jun 27, 2023 22:09 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Easonyesheng/CCS] How to find the distortion correction model?(Issue #6) We recommend you to train a correction model using our data generation code and training scripts. We've try to upload the pretrained correction model, but it is too big to directly upload by git, and this correction method is also sensitive to the specific chessboard pattern. So train your own model is better. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

How to use data generation code and training scripts to train calibration models?
Did you train successfully?

**Comment by xuefeng1130** [comment]
> Hello We recommend you to train a correction model using our data generation code and training scripts. We've try to upload the pretrained correction model, but it is too big to directly upload by git, and this correction method is also sensitive to the specific chessboard pattern. So train your own model is better.

How to use data generation code and training scripts to train calibration models?
Are these paths set up correctly for me? What does each path do?
![image](https://github.com/Easonyesheng/CCS/assets/113966288/ff972474-c159-4bc0-902a-6341188eef04)

Is it a 480*480 image that I need to provide? How many?Does the image need to include the checkerboard grid?
![image](https://github.com/Easonyesheng/CCS/assets/113966288/5344352d-3285-42e9-b312-7e8a70b92f88)

What about the TUM dataset?
<img width="851" alt="image" src="https://github.com/Easonyesheng/CCS/assets/113966288/9f140d01-4eca-4e07-bf6a-5694547592f0">
