### ISSUE TITLE
How to callibrate my own chessboard

### ISSUE THREAD

**Issue by IAMHAADICOOL** [Easonyesheng/CCS#7]
Okay, so I am a little bit confused about the source code provided here😅😅
I have my chessboard images, okay?
I don't have the heatmaps, so should I generate heatmaps myself or are scripts already there in the repository for doing that?
Also, can you please also create a text document or so, explaining how to implement the process in a lucid way please?😅😅

**Comment by Easonyesheng** [comment]
Hi, you may need to read our paper first where we described the total process in detail. You do need to generate heatmaps before calibration and we update a pretrained model for that which may need further fine tuning. If your chessboard gets different size, you may need to train your own model.

**Comment by 123ioup** [comment]
Hi，I have two questions, how to replace my own checkerboard for camera calibration, can not find which module in the model calls the Resnet structure

**Comment by Easonyesheng** [comment]
1. You may need to train your own detection model for your checkerboard.
2. See ./models/ResNet.py, where you can find the resnet.
