### ISSUE TITLE
question: what is the train_txt_path

### ISSUE THREAD

**Issue by njsymanz** [Easonyesheng/CCS#8]
In the two training scripts, there is an empty string train_txt_path that is required but lacks an explanation. The best I could find was the description under the ChessboardDetectDataset class saying `txt saved as: img_path heatmap_path`. If there is a sample text file I missed, that would be helpful as well.

**Comment by Easonyesheng** [comment]
Hi~
The ```train_txt_path``` is a path of a txt file for training, which contains paths of training data.
Taking the Chessboard Corner Detection model as an example, this txt file gets `n' lines and each line is ```f"{chessboard_img_path, e.g. ../../../xxx.jpg} {heatmap_path e.g. ../../xxx.npy}"```.
I hope this description will be helpful.

**Comment by 123ioup** [comment]
> Hi~ The `train_txt_path` is a path of a txt file for training, which contains paths of training data. Taking the Chessboard Corner Detection model as an example, this txt file gets `n' lines and each line is `f"{chessboard_img_path, e.g. ../../../xxx.jpg} {heatmap_path e.g. ../../xxx.npy}"`. I hope this description will be helpful.

Can you send a txt file example?

**Comment by Easonyesheng** [comment]
Examples as follows.
``` txt
/home/sd/CCS/train/chessboard_img_folder/0001.jpg /home/sd/CCS/train/heatmap_folder/0001.npy
/home/sd/CCS/train/chessboard_img_folder/0002.jpg /home/sd/CCS/train/heatmap_folder/0002.npy
...
```

**Comment by 123ioup** [comment]
非常感谢你的回答，同学，可以加个联系方式详细聊一下吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Easonyesheng/CCS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Easonyesheng/CCS] question: what is the train_txt_path (Issue #8)





 
Examples as follows.
 
/home/sd/CCS/train/chessboard_img_folder/0001.jpg /home/sd/CCS/train/heatmap_folder/0001.npy
 /home/sd/CCS/train/chessboard_img_folder/0002.jpg /home/sd/CCS/train/heatmap_folder/0002.npy
 ...
