### ISSUE TITLE
wrong results on demo_light

### ISSUE THREAD

**Issue by tazalapizza** [Easonyesheng/CCS#9]
Hello, thank you for your code and paper.

I tried to test your code using the corner detection weights you provided, with Demo_calib.py.
It works well on the demo_noise images, but it fails on the demo_light images.
The corner detection founds a maximum of 28 out of 30 corners. But in the DetectRes heatmap you uploaded, all corners are found.

With uploaded model
![new](https://github.com/Easonyesheng/CCS/assets/44235349/d26d78ec-17d1-466c-97e8-980e0b05ef9b)

What you have
![old](https://github.com/Easonyesheng/CCS/assets/44235349/a2a2f8f6-132c-4125-83ac-e16d85308648)

Is the corner detection model you uploaded not the same one ?
I also tried to train a model on other sizes of chessboards, the losses converged but it is not performing well. Can you help ? Thanks.
![train](https://github.com/Easonyesheng/CCS/assets/44235349/d09e2519-b592-42b6-b36d-09794df54252)

**Comment by Easonyesheng** [comment]
Hi~ Thank you for the reminder.

1. **The uploaded model is actually a basic model which is trained on dataset without uneven illumination, which can be fine-tuned on the enhanced dataset.** The chessboard images with bad lighting can also be generated by our code. I will find the corresponding model for the demo and upload it when available. 
2. For the abnormal performance, I think it may be related to your training data which have _different patterns_ with the real one. On the other word, if the model is trained on the synthetic data and test on the real data, I recommend to generate chessboard images similar to real ones. I note there are significant responses on the edge of the chessboard (the last image). This could be one of the inconsistent patterns mentioned above, and you can generate similar edges for synthetic images by modifying our code.
3. As the chessboard corner is some kind of a fixed pattern (like you only need one real chessboard for calibration, so you can train your specific model), the generalization issue of learning models in this task can be alleviated by proper synthetic data augmentation.

**Comment by 123ioup** [comment]
> Hi~ Thank you for the reminder.
> 
> 1. **The uploaded model is actually a basic model which is trained on dataset without uneven illumination, which can be fine-tuned on the enhanced dataset.** The chessboard images with bad lighting can also be generated by our code. I will find the corresponding model for the demo and upload it when available.
> 2. For the abnormal performance, I think it may be related to your training data which have _different patterns_ with the real one. On the other word, if the model is trained on the synthetic data and test on the real data, I recommend to generate chessboard images similar to real ones. I note there are significant responses on the edge of the chessboard (the last image). This could be one of the inconsistent patterns mentioned above, and you can generate similar edges for synthetic images by modifying our code.
> 3. As the chessboard corner is some kind of a fixed pattern (like you only need one real chessboard for calibration, so you can train your specific model), the generalization issue of learning models in this task can be alleviated by proper synthetic data augmentation.



> Hi~ Thank you for the reminder.
> 
> 1. **The uploaded model is actually a basic model which is trained on dataset without uneven illumination, which can be fine-tuned on the enhanced dataset.** The chessboard images with bad lighting can also be generated by our code. I will find the corresponding model for the demo and upload it when available.
> 2. For the abnormal performance, I think it may be related to your training data which have _different patterns_ with the real one. On the other word, if the model is trained on the synthetic data and test on the real data, I recommend to generate chessboard images similar to real ones. I note there are significant responses on the edge of the chessboard (the last image). This could be one of the inconsistent patterns mentioned above, and you can generate similar edges for synthetic images by modifying our code.
> 3. As the chessboard corner is some kind of a fixed pattern (like you only need one real chessboard for calibration, so you can train your specific model), the generalization issue of learning models in this task can be alleviated by proper synthetic data augmentation.

How to train the model with real data instead of generated virtual data, can you give a detailed explanation.thank you
